config/routes.rb
Rails.application.routes.draw do
  root to: 'dogs#index'
  get 'dogs/new', to: 'dogs#new', as: :new_dog
  get 'dogs/:id', to: 'dogs#show', as: :dog
  patch 'dogs/:id', to: 'dogs#update'
  delete 'dogs/:id', to: 'dogs#destroy'
  post 'dogs', to: 'dogs#create'
  get 'dogs/:id/edit', to: 'dogs#edit', as: :edit_dog
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  CITIES = ["Marseille", "Aix-en-Provence", "Aubagne"]

  validates :name, presence: true
  validates :city, inclusion: { in: CITIES }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.all
  end

  def show
    @dog = Dog.find(params[:id])
  end

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.new(dog_params)
    @dog.image = 'https://images.dog.ceo/breeds/terrier-norfolk/n02094114_2911.jpg'
    @dog.save
    redirect_to dog_path(@dog)
  end

  def edit
    @dog = Dog.find(params[:id])
  end

  def update
    @dog = Dog.find(params[:id])
    @dog.update(dog_params)
    redirect_to dog_path(@dog)
  end

  def destroy
    @dog = Dog.find(params[:id])
    @dog.destroy
    redirect_to root_path
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :city, :found_on)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/edit.html.erb
<h1>Edit: <%= @dog.name %></h1>

<%= simple_form_for(@dog) do |f| %>
  <%= f.input :name %>
  <%= f.input :city, collection: Dog::CITIES  %>
  <%= f.input :found_on %>
  <%= f.submit %>
<% end %>

app/views/dogs/index.html.erb
<h1>Dogs</h1>

<hr>
<% @dogs.each do |dog| %>
  <h2><%= link_to dog.name, dog_path(dog) %></h2>
  <p>Found the <%= dog.found_on %> at <%= dog.city %></p>
  <%= image_tag dog.image, alt: "alttext", height: '80px' %>

  <hr>
<% end %>
<hr>
<%= link_to "+ Add dog", new_dog_path %>
<hr>

app/views/dogs/new.html.erb
<h1>New dog</h1>

<%= simple_form_for(@dog) do |f| %>
  <%= f.input :name %>
  <%= f.input :city, collection: Dog::CITIES  %>
  <%= f.input :found_on %>
  <%= f.submit %>
<% end %>

app/views/dogs/show.html.erb
<h1><%= @dog.name %></h1>
<%= image_tag @dog.image, alt: "alttext" %>
<p>Found the <%= @dog.found_on %> at <%= @dog.city %></p>


<hr>
<%= link_to "Delete", dog_path(@dog), method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to "Edit", edit_dog_path(@dog) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <hr>
    <%= link_to '> Back to list', root_path %>
  </body>
</html>